# Use uma imagem Python como base
FROM python:3.10.11

# Defina o diretório de trabalho
WORKDIR /app

# Copie o código do cliente para o contêiner
COPY client.py /app/client.py

# Execute o cliente quando o contêiner iniciar
CMD ["python", "client.py"]