# Use uma imagem Python como base
FROM python:3.10.11

# Defina o diretório de trabalho
WORKDIR /app

# Copie o código do servidor para o contêiner
COPY server.py /app/server.py

# Instale o MySQL Connector
RUN pip install mysql-connector-python

# Execute o servidor quando o contêiner iniciar
CMD ["python", "server.py"]